name: CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: fjogeleit/http-request-action@master
      with:
        url: 'https://www.kvanli.com/api/blog/refresh'
        method: 'GET'
